/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.25
 * Generated at: 2015-05-19 18:03:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import be.fedict.eid.applet.service.Identity;
import be.fedict.eid.applet.service.Address;

public final class eid_005fresponse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            <!doctype html>\r\n");
      out.write("            <html class=\"no-js\" lang=\"\">\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"utf-8\">\r\n");
      out.write("                <meta name=\"description\" content=\"\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("                <title>webapp</title>\r\n");
      out.write("                <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\r\n");
      out.write("                <!-- build:css styles/vendor.css -->\r\n");
      out.write("                <!-- bower:css -->\r\n");
      out.write("                <!-- endbower -->\r\n");
      out.write("                <!-- endbuild -->\r\n");
      out.write("                <!-- build:css styles/main.css -->\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"/client/styles/main.css\">\r\n");
      out.write("                <!-- endbuild -->\r\n");
      out.write("                <!-- build:js scripts/vendor/modernizr.js -->\r\n");
      out.write("                <script src=\"/bower_components/modernizr/modernizr.js\"></script>\r\n");
      out.write("                <script src=\"/bower_components/jquery/dist/jquery.js\"></script>\r\n");
      out.write("                <!-- endbuild -->\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <form role=\"form\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"firstName\" id=\"firstName\" class=\"form-control input-sm\" placeholder=\"First Name\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"middleName\" id=\"middleName\" class=\"form-control input-sm\" placeholder=\"Middle Name\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"name\" id=\"name\" class=\"form-control input-sm\" placeholder=\"Last Name\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <input type=\"email\" name=\"email\" id=\"email\" class=\"form-control input-sm\" placeholder=\"Email Address\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <input type=\"input\" name=\"nationality\" id=\"nationality\" class=\"form-control input-sm\" placeholder=\"Nationality\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-6 col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"nationalNumber\" id=\"nationalNumber\" class=\"form-control input-sm\" placeholder=\"National number\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-6 col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"cardNumber\" id=\"cardNumber\" class=\"form-control input-sm\" placeholder=\"Card number\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-6 col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"placeOfBirth\" id=\"placeOfBirth\" class=\"form-control input-sm\" placeholder=\"Place of birth\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-6 col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"dateOfBirth\" id=\"dateOfBirth\" class=\"form-control input-sm\" placeholder=\"Date of birth\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"streetAndNumber\" id=\"streetAndNumber\" class=\"form-control input-sm\" placeholder=\"Street and number\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"zip\" id=\"zip\" class=\"form-control input-sm\" placeholder=\"Zip code\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"municipality\" id=\"municipality\" class=\"form-control input-sm\" placeholder=\"Municipality\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-6 col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input disabled=\"true\" type=\"text\" name=\"cardValidityDateBegin\" id=\"cardValidityDateBegin\" class=\"form-control input-sm\" placeholder=\"Card validity begin date\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-6 col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input disabled=\"true\" type=\"text\" name=\"cardValidityDateEnd\" id=\"cardValidityDateEnd\" class=\"form-control input-sm\" placeholder=\"Card validity end date\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-6 col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <button type=\"button\" id=\"btnCancel\" class=\"btn btn-info btn-block\">Cancel</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-xs-12 col-sm-6 col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"submit\" id=\"btnReadId\" value=\"Submit\" class=\"btn btn-info btn-block\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("                <!--[if lt IE 10]>\r\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("                <script src=\"/client/scripts/deployJava_mod.js\"></script>\r\n");
      out.write("\r\n");
      out.write("                <script type=\"text/javascript\">\r\n");
      out.write("                    $(document).ready(function () {\r\n");
      out.write("                        var eidData = {\r\n");
      out.write("                            firstName: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).firstName);
      out.write("\",\r\n");
      out.write("                            name: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).name);
      out.write("\",\r\n");
      out.write("                            middleName: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).middleName);
      out.write("\",\r\n");
      out.write("                            nationalNumber: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).nationalNumber);
      out.write("\",\r\n");
      out.write("                            dateOfBirth: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).dateOfBirth.getTime());
      out.write("\",\r\n");
      out.write("                            placeOfBirth: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).placeOfBirth);
      out.write("\",\r\n");
      out.write("                            nationality: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).nationality);
      out.write("\",\r\n");
      out.write("                            address: {\r\n");
      out.write("                                streetAndNumber: \"");
      out.print(((Address) session.getAttribute("eid.address")).streetAndNumber);
      out.write(" \",\r\n");
      out.write("                                zip: \"");
      out.print(((Address) session.getAttribute("eid.address")).zip);
      out.write(" \",\r\n");
      out.write("                                municipality: \"");
      out.print(((Address) session.getAttribute("eid.address")).municipality);
      out.write("\"\r\n");
      out.write("                            },\r\n");
      out.write("                            cardNumber: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).cardNumber);
      out.write("\",\r\n");
      out.write("                            cardValidityDateBegin: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).cardValidityDateBegin.getTime());
      out.write("\",\r\n");
      out.write("                            cardValidityDateEnd: \"");
      out.print(((Identity) session.getAttribute("eid.identity")).cardValidityDateEnd.getTime());
      out.write("\",\r\n");
      out.write("                            photo: \"https://www.idlog.be:9080/photo.jpg\"\r\n");
      out.write("                        };\r\n");
      out.write("                        $(\"#btnReadId\").on('click', function () {\r\n");
      out.write("                            window.opener.postMessage(eidData, \"http://www.idlog.be:9000/input\");\r\n");
      out.write("                            window.close();\r\n");
      out.write("\r\n");
      out.write("                        })\r\n");
      out.write("                        $(\"#btnCancel\").on('click', function () {\r\n");
      out.write("                            window.close();\r\n");
      out.write("\r\n");
      out.write("                        })\r\n");
      out.write("                        \r\n");
      out.write("                        $('#firstName').val(eidData.firstName);\r\n");
      out.write("                        $('#name').val(eidData.name);\r\n");
      out.write("                        $('#middleName').val(eidData.middleName);\r\n");
      out.write("                        $('#nationalNumber').val(eidData.nationalNumber);\r\n");
      out.write("                        $('#dateOfBirth').val(eidData.dateOfBirth);\r\n");
      out.write("                        $('#placeOfBirth').val(eidData.placeOfBirth);\r\n");
      out.write("                        $('#nationality').val(eidData.nationality);\r\n");
      out.write("                        $('#streetAndNumber').val(eidData.address.streetAndNumber);\r\n");
      out.write("                        $('#zip').val(eidData.address.zip);\r\n");
      out.write("                        $('#municipality').val(eidData.address.municipality);\r\n");
      out.write("                        $('#cardNumber').val(eidData.cardNumber);\r\n");
      out.write("                        $('#cardValidityDateBegin').val(eidData.cardValidityDateBegin);\r\n");
      out.write("                        $('#cardValidityDateEnd').val(eidData.cardValidityDateEnd);\r\n");
      out.write("                        $('#idPhoto').attr(\"src\", eidData.photo);\r\n");
      out.write("                    });\r\n");
      out.write("                </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
