/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.25
 * Generated at: 2015-03-23 05:57:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import javax.sql.*;
import java.sql.*;
import java.text.*;
import com.easypaygroup.snolf.*;

public final class eid_002dlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/inc/conn.inc", Long.valueOf(1349431053000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html> \r\n");
      out.write('\r');
      out.write('\n');


      response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
      response.setHeader("Pragma","no-cache"); //HTTP 1.0
      response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

      String lang = "nl";
      //Context initContext = new InitialContext();
      //Context envContext = (Context) initContext.lookup("java:/comp/env");
      //DataSource ds = (DataSource) envContext.lookup("jdbc/SVF_dev");
      //Connection conn = ds.getConnection();


      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 
  be.fedict.eid.applet.service.EIdData eid = (be.fedict.eid.applet.service.EIdData)session.getAttribute( "eid" ); 
 
  String b = request.getParameter("b");
  String s = request.getParameter("s"); 
 
  if (eid == null) {
    response.sendRedirect("http://eppc0509");
  } else {

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\"> \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/algemeen/scripts/index.css\">\r\n");
      out.write("        <script src=\"algemeen/scripts/aes.js\"></script>  \r\n");
      out.write("        <script type=\"text/javascript\" src=\"/algemeen/scripts/jquery.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/algemeen/scripts/env_config.js\"></script>         \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("  <div id=\"identbox\">\r\n");
      out.write("      <section id=\"eidpicture\">\r\n");
      out.write("        <img id=\"picture\" src=\"photo.jpg\" />\r\n");
      out.write("      </section>\r\n");
      out.write("      <section id=\"eiddata\">\r\n");
      out.write("        <ul>          \r\n");
      out.write("          <li><span class=\"label\">Name : </span><span class=\"value\"><b>");
      out.print( eid.getIdentity().getName());
      out.write("</b></span><span class=\"value\">");
      out.print( ", " + eid.getIdentity().getFirstName() + " " + eid.getIdentity().getMiddleName());
      out.write("</span></li>\r\n");
      out.write("          <li><span class=\"label\">National number : </span><span class=\"value\">");
      out.print( eid.getIdentity().getNationalNumber());
      out.write("</span></li>\r\n");
      out.write("          <li><span class=\"label\">Date - place of birth : </span><span class=\"value\">");
      out.print( new SimpleDateFormat("dd.MM.yyyy").format(eid.getIdentity().getDateOfBirth().getTime()) + " - " + eid.getIdentity().getPlaceOfBirth());
      out.write("</span></li>\r\n");
      out.write("          <li><span class=\"label\">Nationality : </span><span class=\"value\">");
      out.print( eid.getIdentity().getNationality());
      out.write("</span></li>\r\n");
      out.write("          <li><br/></li>\r\n");
      out.write("          <li><span class=\"label\">Address : </span><span class=\"value\">");
      out.print( eid.getAddress().getStreetAndNumber());
      out.write("</span></li>\r\n");
      out.write("          <li><span class=\"label\">&nbsp;</span><span class=\"value\">");
      out.print( eid.getAddress().getZip() + " " + eid.getAddress().getMunicipality());
      out.write("</span></li>\r\n");
      out.write("          <li><br/></li>\r\n");
      out.write("          <li><span class=\"label\">Cardnumber : </span><span class=\"value\">");
      out.print( eid.getIdentity().getCardNumber());
      out.write("</span></li>\r\n");
      out.write("          <li><span class=\"label\">Cardvalidity : </span><span class=\"value\">");
      out.print( new SimpleDateFormat("dd.MM.yyyy").format(eid.getIdentity().getCardValidityDateBegin().getTime()) + " - " + new SimpleDateFormat("dd.MM.yyyy").format(eid.getIdentity().getCardValidityDateEnd().getTime()));
      out.write("</span></li>\r\n");
      out.write("          <li><span class=\"label\">Issued by : </span><span class=\"value\">");
      out.print( eid.getIdentity().getCardDeliveryMunicipality());
      out.write("</span></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </section>\r\n");
      out.write("      <div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"sboxes\">\r\n");
      out.write("  </div>\r\n");
      out.write("</div>     \r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("        eidIdentifier =  ");
      out.print(eid.getIdentifier());
      out.write(";\r\n");
      out.write("        eidIdentifier2 = ");
      out.print( s);
      out.write(";\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");

  }
  session.setAttribute( "eid", null);    

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
