/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.25
 * Generated at: 2015-03-21 20:20:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class eid_002dauth_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\">\n");
      out.write("  <style>\n");
      out.write("          html, body {\n");
      out.write("            margin: 0px;\n");
      out.write("            padding: 0px;\n");
      out.write("            font-size: 12pt;\n");
      out.write("            height: 100%;\n");
      out.write("            width: 100%;\n");
      out.write("          }\n");
      out.write("          #container {\n");
      out.write("            display: block;\n");
      out.write("            position: relative;\n");
      out.write("            width: 800px;\n");
      out.write("            margin: auto;\n");
      out.write("            border: 2px solid #000;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            top: 15%;\n");
      out.write("          }\n");
      out.write("          #clientlogo {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 3px;\n");
      out.write("            left: 3px;\n");
      out.write("            width: 100px;\n");
      out.write("            height: 100px;\n");
      out.write("\n");
      out.write("            background: url('algemeen/images/gridlogo.png') no-repeat;\n");
      out.write("            background-size: 80px auto;\n");
      out.write("          }\n");
      out.write("          #easypaylogo {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 3px;\n");
      out.write("            right: 3px;\n");
      out.write("            width: 100px;\n");
      out.write("            height: 100px;\n");
      out.write("\n");
      out.write("            background: url('algemeen/images/easypaylogo.png') no-repeat;\n");
      out.write("            background-size: 100px auto;\n");
      out.write("          }\n");
      out.write("          #header {\n");
      out.write("            display: block;\n");
      out.write("            height: 100px;\n");
      out.write("          }\n");
      out.write("          .link {\n");
      out.write("            display: block;\n");
      out.write("            clear: both;\n");
      out.write("            margin: auto;\n");
      out.write("            width: 600px;\n");
      out.write("          }\n");
      out.write("          a {\n");
      out.write("            color: SteelBlue;\n");
      out.write("          }\n");
      out.write("          a:hover {\n");
      out.write("            text-decoration: none;\n");
      out.write("          }\n");
      out.write("          .linktext {\n");
      out.write("            display: block;\n");
      out.write("            float: left;\n");
      out.write("            line-height: 64px;\n");
      out.write("          }\n");
      out.write("          .img {\n");
      out.write("            float: left;\n");
      out.write("            display: block;\n");
      out.write("            width: 128px;\n");
      out.write("            height: 128px;\n");
      out.write("          }\n");
      out.write("          #own_img {\n");
      out.write("            background: url('algemeen/images/sc_secure.png') no-repeat;\n");
      out.write("            background-size: 128px auto;\n");
      out.write("          }\n");
      out.write("          #admin_img {\n");
      out.write("            background: url('algemeen/images/sc_admin.png') no-repeat;\n");
      out.write("            background-size: 128px auto;\n");
      out.write("          }\n");
      out.write("  </style>\n");
      out.write("  <script type=\"text/javascript\" src=\"/algemeen/scripts/jquery.js\"></script>\n");
      out.write("  <script src=\"algemeen/scripts/deployJava.js\"></script>\n");
      out.write("  <script>\n");
      out.write("  $(document).ready(function() {\n");
      out.write("    $('#own').click(function() {\n");
      out.write("      run(0, 0);\n");
      out.write("      return false;\n");
      out.write("    });\n");
      out.write("    $('#admin').click(function() {\n");
      out.write("      run(1, prompt(\"Rijksregisternummer gebruiker | Numéro national de l'utilisateur :\",0));\n");
      out.write("      return false;\n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("  function run(admin, ssin) {\n");
      out.write("    var attributes = {\n");
      out.write("    code :'be.fedict.eid.applet.Applet.class',\n");
      out.write("    archive :'easypay/program/eid-applet-package-1.2.0.Beta3.jar',\n");
      out.write("    width :400,\n");
      out.write("    height :300\n");
      out.write("    };\n");
      out.write("    var parameters = {\n");
      out.write("    TargetPage :'eid-login.jsp?b=' + admin + '&s='+ssin,\n");
      out.write("    AppletService : 'easypay/program;jsessionid=");
      out.print(session.getId());
      out.write(" ',\n");
      out.write("    BackgroundColor : '#ffffff',\n");
      out.write("    HideDetailsButton : 'true'\n");
      out.write("    };\n");
      out.write("    var version = '1.6';\n");
      out.write("    deployJava.runApplet(attributes, parameters, version);\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div id=\"container\">\n");
      out.write("    <div id=\"clientlogo\">\n");
      out.write("    </div>\n");
      out.write("    <div id=\"easypaylogo\">\n");
      out.write("    </div>\n");
      out.write("    <div id=\"header\"></div>\n");
      out.write("    <div class=\"link\">\n");
      out.write("      <div id=\"own_img\" class=\"img\"></div>\n");
      out.write("      <div class=\"linktext\">\n");
      out.write("        <a href=\"#\" id=\"own\" class=\"choice\">Inloggen in EASYSVF met eigen identiteitskaart. <br> Connectez avec EASYCAS avec votre propre carte d'identité</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"link\">\n");
      out.write("      <div id=\"admin_img\" class=\"img\"></div>\n");
      out.write("      <div class=\"linktext\">\n");
      out.write("        <a href=\"#\" id=\"admin\" class=\"choice\">Inloggen in EASYSVF met administrator identiteitskaart. <br> Connectez avec EASYCAS avec une carte d'identité d'un administrateur</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"link\"></div>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
